name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    
    steps:       
    - name: Deploy using ssh
      uses: actions/checkout@v1
      
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/ec2-user/github/
          sudo apt-get -y update
          sudo apt-get install -y apache2
          sudo systemctl start apache2
          sudo systemctl enable apache2
          cd home
          sudo mv * /var/www/html
          # sudo yum -y install httpd
          # sudo service httpd start
          # sudo systmctl enable httpd
          # echo '<!doctype html>' >> /var/www/html/index.html
          # echo '<html>' >> /var/www/html/index.html
          # echo '<head>' >> /var/www/html/index.html
          # echo '<title>This is the title of the webpage!</title>' >> /var/www/html/index.html
          # echo '</head>' >> /var/www/html/index.html
          # echo '</html>' >> /var/www/html/index.html
           
                
       
